-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 23:38:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema onion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onion` DEFAULT CHARACTER SET utf8 ;
USE `onion` ;

-- -----------------------------------------------------
-- Table `onion`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onion`.`perfil` (
  `idPerfil` INT(11) NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `onion`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onion`.`login` (
  `idLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `idPerfil` INT(11) NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_login_perfil1_idx` (`idPerfil` ASC) ,
  CONSTRAINT `fk_login_perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `onion`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `onion`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onion`.`administrador` (
  `idAdm` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeAdm` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `idPerfil` INT(11) NOT NULL DEFAULT 1,
  `idLogin` INT(11) NOT NULL,
  PRIMARY KEY (`idAdm`),
  INDEX `fk_administrador_perfil1_idx` (`idPerfil` ASC) ,
  INDEX `fk_administrador_login1_idx` (`idLogin` ASC) ,
  CONSTRAINT `fk_administrador_login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `onion`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `onion`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `onion`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onion`.`empresa` (
  `idEmpresa` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeEmpresa` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(60) NOT NULL,
  `idPerfil` INT(11) NOT NULL DEFAULT 2,
  `idLogin` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_empresa_perfil1_idx` (`idPerfil` ASC) ,
  INDEX `fk_empresa_login1_idx` (`idLogin` ASC) ,
  CONSTRAINT `fk_empresa_login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `onion`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `onion`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `onion`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onion`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `idEmpresa` INT(11) NULL DEFAULT NULL,
  `idLogin` INT(11) NOT NULL,
  `idPerfil` INT(11) NOT NULL DEFAULT 3,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Empresa1_idx` (`idEmpresa` ASC) ,
  INDEX `fk_cliente_login1_idx` (`idLogin` ASC) ,
  INDEX `fk_cliente_perfil1_idx` (`idPerfil` ASC) ,
  CONSTRAINT `fk_Cliente_Empresa1`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `onion`.`empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `onion`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `onion`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `onion`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onion`.`servico` (
  `idServico` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeServico` VARCHAR(45) NOT NULL,
  `tempo` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `idLogin` INT(11) NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_servico_login1_idx` (`idLogin` ASC) ,
  CONSTRAINT `fk_servico_login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `onion`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
